### ISSUE TITLE
How to use it  for Chinese words ？

### ISSUE THREAD

**Issue by c1a1o1** [geek-ai/Texygen#12]
How to use it  for Chinese words ？

**Comment by Yaoming95** [comment]
We offer data/shi.txt as a Chinese training set. You can just run `python main.py -g seqgan -t real -d data/shi.txt`
Or you can use your own dataset, where each character must be separated by spaces, just like in shi.txt
`秦 川 雄 帝 宅 ， 函 谷 壮 皇 居 。 绮 殿 千 寻 起 ， 离 宫 百 雉 余 。 `

**Comment by c1a1o1** [comment]
thank you very much! It is a great work!
