### ISSUE TITLE
怎样跑自己的真实数据

### ISSUE THREAD

**Issue by letmeheard** [geek-ai/Texygen#38]

**Comment by letmeheard** [comment]
采用'real'方式时，到底哪个文件是根据自己的数据集生成的文本呢

**Comment by letmeheard** [comment]
> 嘿！我将参数设置为 args = ['-g', 'seqgan', '-t', 'real','-d','data/image_coco.txt']
> 为什么save中的generator.txt仍然生成的是一堆数字而不是文本呢

**Comment by WuJ1n9** [comment]
@letmeheard请问问题解决了吗，我这边也是一样。谢谢
