### ISSUE TITLE
BLEU of LeakGAN is much lower than in the original paper

### ISSUE THREAD

**Issue by AranKomat** [geek-ai/Texygen#7]
BLEU-2 of LeakGAN in WMT is 0.956 in the original paper, whereas it's 0.835 here. Notably, BLEU score of LeakGAN and that of other models for COCO diminished in your benchmark. Do you know what caused the difference? In order to compare my model with the ones in your benchmark, am I supposed to make every words in lower case by using .lower() as suggested in text_process.py? Lower-case-only generation wasn't done in LeakGAN, which regarded 'A' and 'a' to be different, so that may be one factor for the aforementioned difference.

**Comment by MichaelZhouwang** [comment]
Hi, why is this issue closed?  Could you please explain the reason of lower performance? I'm confused about this issue, thanks a lot!
