### ISSUE TITLE
How does the operator '@' work?

### ISSUE THREAD

**Issue by DaoD** [geek-ai/Texygen#9]
To whom it may concern,

Hi, I find a problem in the RankGAN code.  The link is [here](https://github.com/geek-ai/Texygen/blob/08c67a1fc37d9b3ec923ac9e3b6daeabce79fa3f/models/rankgan/RankganDiscriminator.py#L191)

self.scores = tf.reshape(self.feature @ tf.transpose(self.reference, perm=[1, 0]), [-1])

I wonder how does this operator @ work.

Thanks.

**Comment by desire2020** [comment]
Hello, for python 3.x, TensorFlow supports operator @, which stands for matrix multiplication.
Hope this helps.

**Comment by DaoD** [comment]
@desire2020 Thanks.
